### ISSUE TITLE
mastr.rb runtime error

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/Mastr#4]
I was playing around with this today trying to get it to run, just to see what kind of output I get. 

`$ ruby mastr.rb diff-eq/C1
mastr.rb:23:in 'block in <main>': undefined method 'result_with_hash' for #<ERB:0x00000000c65728> (NoMethodError)
	from mastr.rb:17:in 'each'
	from mastr.rb:17:in '<main>'
`

Having trouble debugging this one on my own. Problem could be on my end, but I am not sure how to tell.

**Comment by StevenClontz** [comment]
I think #result_with_hash is new in Ruby 2.5 - what version are you running?


Steven Clontz
https://clontz.org - steven.clontz@gmail.com

**Comment by siwelwerd** [comment]
ruby 2.3.1p112 

I'll update ruby and try again.

**Comment by StevenClontz** [comment]
If you don't want to muck up your system Ruby, you could try this:
https://github.com/rbenv/rbenv#basic-github-checkout (it's what I use to
juggle ruby versions but may be more work than necessary for playing around
with this repo since I eventually want to factor out all the Ruby utilizes
into Python/Sagemath).


Steven Clontz
https://clontz.org - steven.clontz@gmail.com

**Comment by siwelwerd** [comment]
Got it running now, thanks.
